=== NimaSaed/TWT_October_2015/TUT10Q1.dtd
<!ELEMENT cars_catalogue (car*)>
<!ELEMENT car (made, model, color, engine, tran_type)>
<!ATTLIST car year CDATA #REQUIRED>

<!ELEMENT engine (num_of_cylinders, fuel_system)>
<!ELEMENT num_of_cylinders (#PCDATA)>
<!ELEMENT fuel_system (#PCDATA)>

<!ELEMENT made (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT tran_type (#PCDATA)>

=== NimaSaed/TWT_October_2015/TUT10Q1b.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cars_catalogue SYSTEM "TUT10Q1.dtd">

<cars_catalogue>
  <car year="2000">
    <made>
      Toyota
    </made>
    <model>
      corola
    </model>
    <color>
      white
    </color>
    <tran_type>
      auto
    </tran_type>
    <engine>
      <num_of_cylinders>
        4
      </num_of_cylinders>
      <fuel_system>
        n
      </fuel_system>
    </engine>
  </car>
</cars_catalogue>
